[package]
name = "clock"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level     = "s"
codegen-units = 1
debug = false
lto   = true
rpath = false
strip = true

[dependencies]
anyhow = "1.0"

[dependencies.raylib]
version = "4.5"
git = "https://github.com/litten2up/raylib-rs"
branch = "4.5.0"
